insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');
insert into tb_category(name) values ('Electronics');
insert into tb_category(name) values ('Computers');
insert into tb_category(name) values ('Furniture');
insert into tb_category(name) values ('Home Appliances');
insert into tb_category(name) values ('Clothes');

